FieldList:
  extensions:
    - ZenFields
FieldGroup:
  extensions:
    - ZenFieldGroup
FormField:
  extensions:
    - ZenFormField
GridField:
  extensions:
    - ZenGridField
UploadField:
  extensions:
    - ZenUploadField
ZenFields:
  gridfield_sortable_component_classes:
    - GridFieldOrderableRows
    - GridFieldSortableRows